### ISSUE TITLE
example

### ISSUE THREAD

**Issue by bill130** [jordanopos/uganda_mobile_money#2]
help me with a working sample because i have tried but i get.
I/flutter ( 3447): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 3447): │ #0   UgandaMobileMoney.chargeClient (package:uganda_mobile_money/client.dart:36:15)
I/flutter ( 3447): │ #1   <asynchronous suspension>
I/flutter ( 3447): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 3447): │ ⛔ type 'Null' is not a subtype of type 'Map<String, dynamic>'
I/flutter ( 3447): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 3447): Something Went wrong

**Comment by jordanopos** [comment]
hello all should be fixed right now. please let me know if it worked for you
